#! /bin/bash

export VERSION="50-1"
export SYSTEM_DESC="ArtemevOS CachyOS"
export SYSTEM_NAME="artemevos-cachyos"
export USERNAME="gamer"
export SIZE="14000MB"
export ARCHIVE_DATE="2025/01/15"
export WEBSITE="https://artemevos.org"
export DOCUMENTATION_URL="https://artemevos.org/docs"
export BUG_REPORT_URL="https://github.com/ArtemevOS/artemevos/issues"

# Use CachyOS optimized kernel
export KERNEL_PACKAGE="linux-cachyos-lts"
export KERNEL_PACKAGE_ORIGIN="repo"

export PACKAGES="\
	accountsservice \
	acpi_call-dkms \
	acsccid \
	alsa-firmware \
	alsa-utils \
	amd-ucode \
	bash-completion \
	broadcom-wl-dkms \
	btrfs-progs \
	bzip2 \
	cachy-chroot \
	cachyos-cli-installer-new \
	cachyos-fish-config \
	cachyos-hello \
	cachyos-hooks \
	cachyos-kde-settings \
	cachyos-keyring \
	cachyos-mirrorlist \
	cachyos-rate-mirrors \
	cachyos-settings \
	cachyos-v3-mirrorlist \
	cachyos-v4-mirrorlist \
	chwd \
	cifs-utils \
	cpupower \
	diffutils \
	dkms \
	distrobox \
	dmidecode \
	dosbox \
	efibootmgr \
	epiphany \
	ethtool \
	evtest \
	fakeroot \
	ffmpeg \
	file \
	ffmpegthumbnailer \
	firejail \
	flatpak \
	fmt \
	fuse-zip \
	fuse2 \
	fwupd \
	gamescope \
	gdm \
	git \
	gnome-browser-connector \
	gnome-console \
	gnome-control-center \
	gnome-disk-utility \
	gnome-keyring \
	gnome-menus \
	gnome-session \
	gnome-shell \
	gnome-software \
	gnome-system-monitor \
	gnome-text-editor \
	gnome-tweaks \
	gst-plugin-pipewire \
	gvfs-smb \
	gvfs-nfs \
	gzip \
	htop \
	intel-gpu-tools \
	intel-media-driver \
	intel-ucode \
	intel-undervolt \
	less \
	lib32-curl \
	lib32-fontconfig \
	lib32-freetype2 \
	lib32-libgpg-error \
	lib32-libnm \
	lib32-libxinerama \
	lib32-libxcrypt-compat \
	lib32-mangohud \
	lib32-openal \
	lib32-pipewire \
	lib32-sdl2 \
	lib32-systemd \
	lib32-vulkan-icd-loader \
	libcurl-gnutls \
	libidn11 \
	libnfc \
	libretro-beetle-pce-fast \
	libretro-beetle-psx-hw \
	libretro-desmume \
	libretro-dolphin \
	libretro-flycast \
	libretro-genesis-plus-gx \
	libretro-kronos \
	libretro-mame \
	libretro-mesen-s \
	libretro-mgba \
	libretro-mupen64plus-next \
	libretro-nestopia \
	libretro-picodrive \
	libretro-ppsspp \
	libretro-shaders-slang \
	libretro-snes9x \
	libxcrypt-compat \
	libxss \
	lightdm \
	linux-cachyos-lts-headers \
	linux-firmware \
	liquidctl \
	logrotate \
	lrzip \
	loupe \
	lshw \
	mangohud \
	mesa \
	mesa-demos \
	modemmanager \
	nano \
	nautilus \
	networkmanager \
	nfs-utils \
	noto-fonts-emoji \
	nss-mdns \
	nvidia-open-dkms \
	opencl-nvidia \
	lib32-opencl-nvidia \
	nvidia-utils \
	lib32-nvidia-utils \
	nvidia-prime \
	openal \
	openrazer-daemon \
	openssh \
	p7zip \
	pipewire \
	pipewire-alsa \
	pipewire-jack \
	pipewire-pulse \
	podman \
	pulsemixer \
	python \
	python-notify2 \
	python-pyscard \
	qtractor \
	realtime-privileges \
	retroarch \
	rsync \
	smbclient \
	sof-firmware \
	sshfs \
	steam \
	sudo \
	tar \
	tree \
	ttf-liberation \
	unace \
	unrar \
	unzip \
	usb_modeswitch \
	usbutils \
	vim \
	vulkan-icd-loader \
	wavpack \
	wget \
	which \
	wireplumber \
	wireless-regdb \
	wqy-zenhei \
	xdg-desktop-portal \
	xdg-desktop-portal-gnome \
	xdg-desktop-portal-wlr \
	xdg-user-dirs-gtk \
	xf86-video-amdgpu \
	xorg-server \
	xz \
	zip \
"

export PACKAGE_OVERRIDES="\
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/25.1.1-chos1-3/lib32-mesa-1--25.1.1.chos1-3-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/25.1.1-chos1-3/lib32-opencl-mesa-1--25.1.1.chos1-3-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/25.1.1-chos1-3/lib32-vulkan-intel-1--25.1.1.chos1-3-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/25.1.1-chos1-3/lib32-vulkan-mesa-layers-1--25.1.1.chos1-3-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/25.1.1-chos1-3/lib32-vulkan-radeon-1--25.1.1.chos1-3-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/25.1.1-chos1-3/mesa-1--25.1.1.chos1-3-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/25.1.1-chos1-3/opencl-mesa-1--25.1.1.chos1-3-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/25.1.1-chos1-3/vulkan-intel-1--25.1.1.chos1-3-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/25.1.1-chos1-3/vulkan-mesa-layers-1--25.1.1.chos1-3-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/25.1.1-chos1-3/vulkan-radeon-1--25.1.1.chos1-3-x86_64.pkg.tar.zst \
	https://archive.archlinux.org/packages/l/libretro-ppsspp/libretro-ppsspp-42704-1-x86_64.pkg.tar.zst \
	https://archive.archlinux.org/packages/i/inputplumber/inputplumber-0.60.7-1-x86_64.pkg.tar.zst \
"

# Each entry is the clone url (https://aur.archlinux.org/{AUR_PACKAGE}.git)
# Which is often the same as the package name but it can be different.
# Check on the AUR webpage if you are unsure
export AUR_PACKAGES="\
	asusctl \
	ayaneo-platform-dkms-git \
	ayn-platform-dkms-git \
	bcm20702a1-firmware \
	boxtron \
	chimera \
	chimeraos-device-quirks-git \
	downgrade \
	evdev-keepalive \
	frzr \
	gamescope-session-steam-git \
	gamescope-session-steam-plus-git \
	gpd-fan-driver-dkms-git \
	hhfc-git \
	hid-msi-claw-dkms-git \
	legendary \
	libretro-dosbox-pure-git \
	libretro-lrps2-git \
	libretro-opera-git \
	libretro-prosystem-git \
	libretro-stella2014-git \
	libretro-virtualjaguar-git \
	linux-firmware-valve \
	kanit-font \
	nintendo-udev \
	opengamepadui-bin \
	opengamepadui-session-git \
	pikaur \
	powerstation-bin \
	python-gbopyrator \
	python-vdf \
	rtl8812au-dkms-git \
	rtl8814au-dkms-git \
	rtl8821au-dkms-git \
	ryzenadj-git \
	steam_notif_daemon \
	steam-powerbuttond-git \
	steam-removable-media-git \
	wyvern \
	xpadneo-dkms-git \
	zenergy-dkms-git \
"

export SERVICES="\
	NetworkManager \
	avahi-daemon \
	bluetooth \
	bluetooth-workaround \
	fstrim.timer \
	home-swapfile.swap \
	inputplumber \
	inputplumber-suspend \
	lightdm \
	nvidia-powerd \
	pcscd.socket \
	powerstation \
	steam-powerbuttond \
	sshd \
	systemd-timesyncd \
	swapfile \
"

export USER_SERVICES="\
	chimera.service \
	pipewire \
	steam-patch.service \
	chimera-cart-monitor.service \
	chimera-nfc-monitor.service \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/usr/share/SFML \
	/usr/share/doc \
	/usr/share/gtk-doc \
	/usr/share/help \
	/usr/share/man \
"

postinstallhook() {
	# Add sudo permissions
	sed -i '/%wheel ALL=(ALL:ALL) ALL/s/^# //g' /etc/sudoers
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/dmidecode -t 11" >/etc/sudoers.d/steam
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/systemctl" >/etc/sudoers.d/systemctl

	# CachyOS Performance optimizations
	echo "kernel.split_lock_mitigate=0" > /etc/sysctl.d/99-cachyos-splitlock.conf
	echo "vm.max_map_count=2147483642" > /etc/sysctl.d/99-cachyos-vm.conf
	echo "net.core.netdev_max_backlog=16384" > /etc/sysctl.d/99-cachyos-network.conf
	echo "net.core.somaxconn=8192" >> /etc/sysctl.d/99-cachyos-network.conf

	# Enable zram if not already done
	echo "zram" > /etc/modules-load.d/zram.conf
	echo "options zram num_devices=1" > /etc/modprobe.d/zram.conf

	# Configure CachyOS keyring if available
	if pacman -Qi cachyos-keyring >/dev/null 2>&1; then
		pacman-key --populate cachyos
	fi

	# Configure GNOME as default desktop session
	echo "[daemon]
DefaultSession=gnome
AutomaticLoginEnable=true
AutomaticLogin=${USERNAME}
" > /etc/gdm/custom.conf

	# Create GNOME session switcher script
	cat > /usr/local/bin/session-select << 'EOF'
#!/bin/bash
# Session selector for ArtemevOS
SESSION="${1:-gnome}"

case "$SESSION" in
    gnome|desktop)
        # Switch to GNOME desktop
        sudo systemctl set-default graphical.target
        sudo systemctl enable gdm
        sudo systemctl disable lightdm || true
        echo "Switched to GNOME desktop session"
        ;;
    gaming|steam)
        # Switch to Steam gaming session
        sudo systemctl set-default graphical.target 
        sudo systemctl enable lightdm
        sudo systemctl disable gdm || true
        echo "Switched to Steam gaming session"
        ;;
    *)
        echo "Usage: session-select [gnome|desktop|gaming|steam]"
        echo "Current session: $(loginctl show-session $(loginctl | grep $(whoami) | awk '{print $1}') -p Type --value)"
        ;;
esac
EOF
	chmod +x /usr/local/bin/session-select

	# Disable Steam auto-start by default - user can enable manually
	mkdir -p /home/${USERNAME}/.config/autostart
	cat > /home/${USERNAME}/.config/autostart/steam.desktop << 'EOF'
[Desktop Entry]
Type=Application
Name=Steam
Exec=steam-runtime %U
NoDisplay=true
StartupNotify=true
MimeType=x-scheme-handler/steam;x-scheme-handler/steamlink;
Hidden=true
EOF
	chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.config

	# download and add racing wheel udev rules
	pushd /usr/lib/udev/rules.d
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-fanatec-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-logitech-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-thrustmaster-wheel-perms.rules
	popd

	# Remove build tools for slimmer image
	rm /usr/share/libalpm/hooks/70-dkms-install.hook
	rm /usr/share/libalpm/hooks/70-dkms-upgrade.hook
	rm /usr/share/libalpm/hooks/71-dkms-remove.hook
	pacman --noconfirm -Rnsdd make gcc dkms ${KERNEL_PACKAGE}-headers

	# remove dolphin shortcut to not clutter up the desktop
	rm -f /usr/share/applications/dolphin-emu.desktop

	# Keep GNOME applications visible, hide gaming-specific ones by default
	echo "NoDisplay=true" >> /usr/share/applications/org.chimeraos.Gamescope.desktop || true
	echo "NoDisplay=true" >> /usr/share/applications/org.chimeraos.app.desktop || true
	
	# Keep Steam available but not auto-launching
	sed -i -e 's/Name=Steam (Runtime)/Name=Steam/' /usr/share/applications/steam.desktop
	# Remove Steam from autostart in desktop environments
	sed -i '/^Exec=/c\Exec=steam-runtime %U' /usr/share/applications/steam.desktop

	# Disable SPDIF/IEC958 audio output to make it more likely the correct HDMI output will be selected by default
	sed -e '/\[Mapping iec958/,+5 s/^/#/' -i '/usr/share/alsa-card-profile/mixer/profile-sets/default.conf'

	# Replace wpctl with a wrapper to work around Steam resetting audio
	if [ -f /usr/bin/wpctl-wrapper ]; then
		mv /usr/bin/wpctl /usr/libexec/wpctl
		mv /usr/bin/wpctl-wrapper /usr/bin/wpctl
	fi

	# Set GNOME as default for new installations
	systemctl set-default graphical.target
	systemctl enable gdm
	systemctl disable lightdm || true
	
	# Create desktop entry for session switching
	cat > /usr/share/applications/artemevos-session-select.desktop << 'EOF'
[Desktop Entry]
Name=ArtemevOS Session Switcher
Comment=Switch between Desktop and Gaming modes
Exec=/usr/local/bin/session-select
Icon=preferences-system
Terminal=false
Type=Application
Categories=System;Settings;
EOF
}
